//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.language_es", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apuntes.
        /// </summary>
        internal static string Apunts {
            get {
                return ResourceManager.GetString("Apunts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículos.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce los términos de búsqueda....
        /// </summary>
        internal static string Cercador {
            get {
                return ResourceManager.GetString("Cercador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string Cercar {
            get {
                return ResourceManager.GetString("Cercar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        internal static string Cognoms {
            get {
                return ResourceManager.GetString("Cognoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta cuenta de usuario aún no ha sido activada. Por favor, revisa la bandeja de entrada y haz click en el enlace que encontrarás en nuestro correo.&lt;br /&gt;Si no has recibido ningún correo, haz click &lt;a href=&quot;/&quot;&gt;aquí&lt;/a&gt; para que te lo volvamos a enviar..
        /// </summary>
        internal static string Compte_desactivat {
            get {
                return ResourceManager.GetString("Compte_desactivat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        internal static string Confirma_password {
            get {
                return ResourceManager.GetString("Confirma_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactar.
        /// </summary>
        internal static string Contacta {
            get {
                return ResourceManager.GetString("Contacta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        internal static string Correu_electronic {
            get {
                return ResourceManager.GetString("Correu_electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        internal static string Data_naixement {
            get {
                return ResourceManager.GetString("Data_naixement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mujer.
        /// </summary>
        internal static string Dona {
            get {
                return ResourceManager.GetString("Dona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los derechos reservados.
        /// </summary>
        internal static string Drets_reservats {
            get {
                return ResourceManager.GetString("Drets_reservats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exámenes.
        /// </summary>
        internal static string Examens {
            get {
                return ResourceManager.GetString("Examens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hombre.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string Inici {
            get {
                return ResourceManager.GetString("Inici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        internal static string Inicia_sessio {
            get {
                return ResourceManager.GetString("Inicia_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No especificado.
        /// </summary>
        internal static string No_especificat {
            get {
                return ResourceManager.GetString("No_especificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papers.
        /// </summary>
        internal static string Papers {
            get {
                return ResourceManager.GetString("Papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFCs.
        /// </summary>
        internal static string PFCs {
            get {
                return ResourceManager.GetString("PFCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prácticas.
        /// </summary>
        internal static string Practiques {
            get {
                return ResourceManager.GetString("Practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate.
        /// </summary>
        internal static string Registrat {
            get {
                return ResourceManager.GetString("Registrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        internal static string Sexe {
            get {
                return ResourceManager.GetString("Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de HotNotes....
        /// </summary>
        internal static string Sobre_HotNotes {
            get {
                return ResourceManager.GetString("Sobre_HotNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        internal static string Tanca_sessio {
            get {
                return ResourceManager.GetString("Tanca_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajos.
        /// </summary>
        internal static string Treballs {
            get {
                return ResourceManager.GetString("Treballs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario o la contraseña introducidos son incorrectos.
        /// </summary>
        internal static string Username_password_incorrecte {
            get {
                return ResourceManager.GetString("Username_password_incorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este nombre de usuario ya existe. Por favor, elije otro..
        /// </summary>
        internal static string Usuari_ja_existent {
            get {
                return ResourceManager.GetString("Usuari_ja_existent", resourceCulture);
            }
        }
    }
}
