//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_ca {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_ca() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.language_ca", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El compte s&apos;ha activat correctament. Ara ja pots iniciar sessió des de la pàgina principal..
        /// </summary>
        internal static string Activar_correcte {
            get {
                return ResourceManager.GetString("Activar_correcte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Afegir matrícula.
        /// </summary>
        internal static string Afegir_matricula {
            get {
                return ResourceManager.GetString("Afegir_matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altres....
        /// </summary>
        internal static string Altres {
            get {
                return ResourceManager.GetString("Altres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anglés.
        /// </summary>
        internal static string Angles {
            get {
                return ResourceManager.GetString("Angles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apunts.
        /// </summary>
        internal static string Apunts {
            get {
                return ResourceManager.GetString("Apunts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Article.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articles.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assignatura.
        /// </summary>
        internal static string Assignatura {
            get {
                return ResourceManager.GetString("Assignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor.
        /// </summary>
        internal static string Autor {
            get {
                return ResourceManager.GetString("Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sembla que encara no t&apos;has matriculat de cap curs. Has de seleccionar com a mínim un curs del qual estar matriculat per a poder pujar-hi documents.&lt;br/&gt;&lt;br/&gt;Si us plau, accedeix a la teva [[LINK_CONFIGURACIO]] i tria un curs del qual estar matriculat..
        /// </summary>
        internal static string Avis_no_matriculat {
            get {
                return ResourceManager.GetString("Avis_no_matriculat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Benvingut.
        /// </summary>
        internal static string Benvingut {
            get {
                return ResourceManager.GetString("Benvingut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carregant.
        /// </summary>
        internal static string Carregant {
            get {
                return ResourceManager.GetString("Carregant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carregant comentaris....
        /// </summary>
        internal static string Carregant_comentaris {
            get {
                return ResourceManager.GetString("Carregant_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrera.
        /// </summary>
        internal static string Carrera {
            get {
                return ResourceManager.GetString("Carrera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Castellà.
        /// </summary>
        internal static string Castella {
            get {
                return ResourceManager.GetString("Castella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Català.
        /// </summary>
        internal static string Catala {
            get {
                return ResourceManager.GetString("Catala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introdueix els termes de cerca....
        /// </summary>
        internal static string Cercador {
            get {
                return ResourceManager.GetString("Cercador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Cercar {
            get {
                return ResourceManager.GetString("Cercar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El codi d&apos;activació és incorrecte. Si aquest és l&apos;enllaç que t&apos;hem enviat al teu correu, si us plau, contacta amb l&apos;administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Codi_activar_incorrecte {
            get {
                return ResourceManager.GetString("Codi_activar_incorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cognoms.
        /// </summary>
        internal static string Cognoms {
            get {
                return ResourceManager.GetString("Cognoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completa el registre a HotNotes.
        /// </summary>
        internal static string Completa_el_registre {
            get {
                return ResourceManager.GetString("Completa_el_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aquest compte d&apos;usuari encara no ha estat activat. Si us plau, revisa la bústia d&apos;entrada i fes clic a l&apos;enllaç que trobaràs al nostre correu.&lt;br /&gt;Si no has rebut cap correu, fes clic &lt;a href=&quot;/&quot;&gt;aquí&lt;/a&gt; per a que te&apos;l tornem a enviar..
        /// </summary>
        internal static string Compte_desactivat {
            get {
                return ResourceManager.GetString("Compte_desactivat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estàs segur de que vols eliminar aquesta matrícula?.
        /// </summary>
        internal static string Confirmar_eliminar_matricula {
            get {
                return ResourceManager.GetString("Confirmar_eliminar_matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contrasenya.
        /// </summary>
        internal static string Confirma_password {
            get {
                return ResourceManager.GetString("Confirma_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacta.
        /// </summary>
        internal static string Contacta {
            get {
                return ResourceManager.GetString("Contacta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correu electrònic.
        /// </summary>
        internal static string Correu_electronic {
            get {
                return ResourceManager.GetString("Correu_electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curs.
        /// </summary>
        internal static string Curs {
            get {
                return ResourceManager.GetString("Curs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cursos matriculats.
        /// </summary>
        internal static string Cursos_matriculats {
            get {
                return ResourceManager.GetString("Cursos_matriculats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Les dades s&apos;han actualitzat correctament..
        /// </summary>
        internal static string Dades_actualitzades {
            get {
                return ResourceManager.GetString("Dades_actualitzades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data de creació.
        /// </summary>
        internal static string Data_creacio {
            get {
                return ResourceManager.GetString("Data_creacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data d&apos;últ. modificació.
        /// </summary>
        internal static string Data_modificat {
            get {
                return ResourceManager.GetString("Data_modificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data de naixement.
        /// </summary>
        internal static string Data_naixement {
            get {
                return ResourceManager.GetString("Data_naixement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descarrega el document.
        /// </summary>
        internal static string Descarregar_document {
            get {
                return ResourceManager.GetString("Descarregar_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documents.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documents de l&apos;assignatura.
        /// </summary>
        internal static string Documents_assignatura {
            get {
                return ResourceManager.GetString("Documents_assignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documents de l&apos;usuari.
        /// </summary>
        internal static string Documents_usuari {
            get {
                return ResourceManager.GetString("Documents_usuari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existeix cap document amb aquest identificador..
        /// </summary>
        internal static string Document_no_existeix {
            get {
                return ResourceManager.GetString("Document_no_existeix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dona.
        /// </summary>
        internal static string Dona {
            get {
                return ResourceManager.GetString("Dona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tots els drets reservats.
        /// </summary>
        internal static string Drets_reservats {
            get {
                return ResourceManager.GetString("Drets_reservats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hi ha resultats.
        /// </summary>
        internal static string DT_sEmptyTable {
            get {
                return ResourceManager.GetString("DT_sEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer.
        /// </summary>
        internal static string DT_sFirst {
            get {
                return ResourceManager.GetString("DT_sFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrant _START_-_END_ de _TOTAL_ resultats.
        /// </summary>
        internal static string DT_sInfo {
            get {
                return ResourceManager.GetString("DT_sInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrant 0 de 0 resultats.
        /// </summary>
        internal static string DT_sInfoEmpty {
            get {
                return ResourceManager.GetString("DT_sInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (filtrats de _MAX_ resultats totals).
        /// </summary>
        internal static string DT_sInfoFiltered {
            get {
                return ResourceManager.GetString("DT_sInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Últim.
        /// </summary>
        internal static string DT_sLast {
            get {
                return ResourceManager.GetString("DT_sLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veure _MENU_ resultats.
        /// </summary>
        internal static string DT_sLengthMenu {
            get {
                return ResourceManager.GetString("DT_sLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Següent.
        /// </summary>
        internal static string DT_sNext {
            get {
                return ResourceManager.GetString("DT_sNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        internal static string DT_sPrevious {
            get {
                return ResourceManager.GetString("DT_sPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtenint resultats....
        /// </summary>
        internal static string DT_sProcessing {
            get {
                return ResourceManager.GetString("DT_sProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cercar: .
        /// </summary>
        internal static string DT_sSearch {
            get {
                return ResourceManager.GetString("DT_sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hi ha resultats.
        /// </summary>
        internal static string DT_sZeroRecords {
            get {
                return ResourceManager.GetString("DT_sZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ja hi ha un usuari registrat amb aquesta adreça de correu electrònic..
        /// </summary>
        internal static string Email_ja_existent {
            get {
                return ResourceManager.GetString("Email_ja_existent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Les dades s&apos;han actualitzat correctament. Tot i així, no podràs entrar fins que hagis activat la nova direcció de correu electrònic. Comprova la teva bústia d&apos;entrada i fes clic a l&apos;enllaç que t&apos;hem enviat..
        /// </summary>
        internal static string Email_modificat {
            get {
                return ResourceManager.GetString("Email_modificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimat [[NOM]],&lt;br/&gt;&lt;br/&gt;Per a completar el registre a HotNotes, visita el següent enllaç: &lt;a href=&quot;[[LINK]]&quot;&gt;[[LINK]]&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;Atentament,&lt;br/&gt;&lt;b&gt;L&apos;equip de HotNotes&lt;/b&gt;..
        /// </summary>
        internal static string Email_registre {
            get {
                return ResourceManager.GetString("Email_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi ha hagut un error durant el procés d&apos;activació. Si us plau, torna-ho a provar en uns minuts.&lt;br /&gt;Si el problema persisteix, contacta amb l&apos;administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Error_activar {
            get {
                return ResourceManager.GetString("Error_activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi ha hagut un error pujant el fitxer. Si us plau, torna-ho a intentar en uns minuts..
        /// </summary>
        internal static string Error_Amazon_S3 {
            get {
                return ResourceManager.GetString("Error_Amazon_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi ha hagut un error enviant el teu comentari. Si us plau, torna-ho a intentar més tard..
        /// </summary>
        internal static string Error_comentant {
            get {
                return ResourceManager.GetString("Error_comentant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error carregant els comentaris.
        /// </summary>
        internal static string Error_comentaris {
            get {
                return ResourceManager.GetString("Error_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi ha hagut un error desconegut..
        /// </summary>
        internal static string Error_desconegut {
            get {
                return ResourceManager.GetString("Error_desconegut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi ha hagut un error al dessubscriure&apos;s d&apos;aquest usuari. Si us plau, torna-ho a provar en uns instants..
        /// </summary>
        internal static string Error_dessubscriure {
            get {
                return ResourceManager.GetString("Error_dessubscriure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No s&apos;ha trobat cap assignatura amb aquest Id..
        /// </summary>
        internal static string Error_id_assignatura {
            get {
                return ResourceManager.GetString("Error_id_assignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No s&apos;ha trobat cap usuari amb aquest Id..
        /// </summary>
        internal static string Error_id_usuari {
            get {
                return ResourceManager.GetString("Error_id_usuari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estàs matriculat d&apos;aquest curs..
        /// </summary>
        internal static string Error_no_matriculat {
            get {
                return ResourceManager.GetString("Error_no_matriculat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No et pots dessubscriure d&apos;un usuari al que no estàs subscrit..
        /// </summary>
        internal static string Error_no_subscrit {
            get {
                return ResourceManager.GetString("Error_no_subscrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi ha hagut un error al pujar el document. Si us plau, torna-ho a provar en uns minuts..
        /// </summary>
        internal static string Error_pujar_document {
            get {
                return ResourceManager.GetString("Error_pujar_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi ha hagut un error durant el procés de registre. Si us plau, torna-ho a provar en uns minuts.&lt;br /&gt;Si el problema persisteix, contacta amb l&apos;administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Error_registre {
            get {
                return ResourceManager.GetString("Error_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi ha hagut un error al subscriure&apos;s a aquest usuari. Si us plau, torna-ho a provar en uns instants..
        /// </summary>
        internal static string Error_subscriure {
            get {
                return ResourceManager.GetString("Error_subscriure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi ha hagut un error a l&apos;hora de valorar aquest document. Si us plau, torna-ho a intentar més tard..
        /// </summary>
        internal static string Error_valoracio {
            get {
                return ResourceManager.GetString("Error_valoracio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriu un comentari..
        /// </summary>
        internal static string Escriu_un_comentari {
            get {
                return ResourceManager.GetString("Escriu_un_comentari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a És un exàmen corregit?.
        /// </summary>
        internal static string Es_examen_corregit {
            get {
                return ResourceManager.GetString("Es_examen_corregit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exàmen.
        /// </summary>
        internal static string Examen {
            get {
                return ResourceManager.GetString("Examen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Examens.
        /// </summary>
        internal static string Examens {
            get {
                return ResourceManager.GetString("Examens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facultat.
        /// </summary>
        internal static string Facultat {
            get {
                return ResourceManager.GetString("Facultat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fitxer.
        /// </summary>
        internal static string Fitxer {
            get {
                return ResourceManager.GetString("Fitxer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inici.
        /// </summary>
        internal static string Inici {
            get {
                return ResourceManager.GetString("Inici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sessió.
        /// </summary>
        internal static string Inicia_sessio {
            get {
                return ResourceManager.GetString("Inicia_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enllaç extern.
        /// </summary>
        internal static string LinkExtern {
            get {
                return ResourceManager.GetString("LinkExtern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enllaç a YouTube.
        /// </summary>
        internal static string LinkYoutube {
            get {
                return ResourceManager.GetString("LinkYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has de ser major d&apos;edat per a registrar-te a HotNotes..
        /// </summary>
        internal static string Major_edat {
            get {
                return ResourceManager.GetString("Major_edat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .doc, .docx, .ppt, .pptx, .odt, .pdf o .txt..
        /// </summary>
        internal static string MimeType_no_practiques {
            get {
                return ResourceManager.GetString("MimeType_no_practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipus d&apos;arxiu pujat no està suportat. Si us plau, puja un arxiu que tingui un dels següents formats:.
        /// </summary>
        internal static string MimeType_no_suportat {
            get {
                return ResourceManager.GetString("MimeType_no_suportat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .doc, .docx, .ppt, .pptx, .odt, .pdf, .txt o .zip..
        /// </summary>
        internal static string MimeType_practiques {
            get {
                return ResourceManager.GetString("MimeType_practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar dades.
        /// </summary>
        internal static string Modificar_dades {
            get {
                return ResourceManager.GetString("Modificar_dades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nom.
        /// </summary>
        internal static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No especificat.
        /// </summary>
        internal static string No_especificat {
            get {
                return ResourceManager.GetString("No_especificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hi ha cap comentari en aquest document..
        /// </summary>
        internal static string No_hi_ha_comentaris {
            get {
                return ResourceManager.GetString("No_hi_ha_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tanquis la sessió automàticament.
        /// </summary>
        internal static string No_tanquis_sessio {
            get {
                return ResourceManager.GetString("No_tanquis_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pàgina de configuració.
        /// </summary>
        internal static string Pagina_configuracio {
            get {
                return ResourceManager.GetString("Pagina_configuracio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paper.
        /// </summary>
        internal static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Papers.
        /// </summary>
        internal static string Papers {
            get {
                return ResourceManager.GetString("Papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasenya.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Les contrasenyes no coincideixen..
        /// </summary>
        internal static string Passwords_no_coincideixen {
            get {
                return ResourceManager.GetString("Passwords_no_coincideixen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contrasenya ha de tenir com a mínim 6 caràcters..
        /// </summary>
        internal static string Password_curta {
            get {
                return ResourceManager.GetString("Password_curta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Projecte final de carrera.
        /// </summary>
        internal static string PFC {
            get {
                return ResourceManager.GetString("PFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PFCs.
        /// </summary>
        internal static string PFCs {
            get {
                return ResourceManager.GetString("PFCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pràctica.
        /// </summary>
        internal static string Practica {
            get {
                return ResourceManager.GetString("Practica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pràctiques.
        /// </summary>
        internal static string Practiques {
            get {
                return ResourceManager.GetString("Practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pujar.
        /// </summary>
        internal static string Pujar {
            get {
                return ResourceManager.GetString("Pujar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pujar document.
        /// </summary>
        internal static string Pujar_Document {
            get {
                return ResourceManager.GetString("Pujar_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar-se.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístra&apos;t.
        /// </summary>
        internal static string Registrat {
            get {
                return ResourceManager.GetString("Registrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registre s&apos;ha completat satisfactòriament. No obstant, abans de poder entrar, has de revisar la teva direcció de correu i fer clic a l&apos;enllaç que t&apos;hem enviat per activar el teu compte..
        /// </summary>
        internal static string Registre_completat {
            get {
                return ResourceManager.GetString("Registre_completat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta.
        /// </summary>
        internal static string Ruta {
            get {
                return ResourceManager.GetString("Ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexe.
        /// </summary>
        internal static string Sexe {
            get {
                return ResourceManager.GetString("Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobre HotNotes....
        /// </summary>
        internal static string Sobre_HotNotes {
            get {
                return ResourceManager.GetString("Sobre_HotNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tanca sessió.
        /// </summary>
        internal static string Tanca_sessio {
            get {
                return ResourceManager.GetString("Tanca_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipus.
        /// </summary>
        internal static string Tipus {
            get {
                return ResourceManager.GetString("Tipus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Treball.
        /// </summary>
        internal static string Treball {
            get {
                return ResourceManager.GetString("Treball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Treballs.
        /// </summary>
        internal static string Treballs {
            get {
                return ResourceManager.GetString("Treballs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Universitat.
        /// </summary>
        internal static string Universitat {
            get {
                return ResourceManager.GetString("Universitat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nom d&apos;usuari.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nom d&apos;usuari ha de tenir com a mínim 6 caràcters..
        /// </summary>
        internal static string Username_curt {
            get {
                return ResourceManager.GetString("Username_curt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nom d&apos;usuari o la contrasenya introduïts són incorrectes.
        /// </summary>
        internal static string Username_password_incorrecte {
            get {
                return ResourceManager.GetString("Username_password_incorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aquest nom d&apos;usuari ja existeix. Si us plau, tria&apos;n un altre..
        /// </summary>
        internal static string Usuari_ja_existent {
            get {
                return ResourceManager.GetString("Usuari_ja_existent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existeix cap usuari amb aquest codi..
        /// </summary>
        internal static string Usuari_no_existeix {
            get {
                return ResourceManager.GetString("Usuari_no_existeix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoració.
        /// </summary>
        internal static string Valoracio {
            get {
                return ResourceManager.GetString("Valoracio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versió.
        /// </summary>
        internal static string Versio {
            get {
                return ResourceManager.GetString("Versio", resourceCulture);
            }
        }
    }
}
