//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.language_es", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta se ha activado correctamente. Ahora ya puedes iniciar sesión desde la página principal..
        /// </summary>
        internal static string Activar_correcte {
            get {
                return ResourceManager.GetString("Activar_correcte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros....
        /// </summary>
        internal static string Altres {
            get {
                return ResourceManager.GetString("Altres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        internal static string Angles {
            get {
                return ResourceManager.GetString("Angles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apuntes.
        /// </summary>
        internal static string Apunts {
            get {
                return ResourceManager.GetString("Apunts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículo.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículos.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignatura.
        /// </summary>
        internal static string Assignatura {
            get {
                return ResourceManager.GetString("Assignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string Autor {
            get {
                return ResourceManager.GetString("Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando.
        /// </summary>
        internal static string Carregant {
            get {
                return ResourceManager.GetString("Carregant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando comentarios....
        /// </summary>
        internal static string Carregant_comentaris {
            get {
                return ResourceManager.GetString("Carregant_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castellano.
        /// </summary>
        internal static string Castella {
            get {
                return ResourceManager.GetString("Castella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalán.
        /// </summary>
        internal static string Catala {
            get {
                return ResourceManager.GetString("Catala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce los términos de búsqueda....
        /// </summary>
        internal static string Cercador {
            get {
                return ResourceManager.GetString("Cercador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string Cercar {
            get {
                return ResourceManager.GetString("Cercar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de activación es incorrecto. Si éste es el enlace que te hemos enviado a tu correo, por favor, contacta con el administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Codi_activar_incorrecte {
            get {
                return ResourceManager.GetString("Codi_activar_incorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        internal static string Cognoms {
            get {
                return ResourceManager.GetString("Cognoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completa el registro en HotNotes.
        /// </summary>
        internal static string Completa_el_registre {
            get {
                return ResourceManager.GetString("Completa_el_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta cuenta de usuario aún no ha sido activada. Por favor, revisa la bandeja de entrada y haz click en el enlace que encontrarás en nuestro correo.&lt;br /&gt;Si no has recibido ningún correo, haz click &lt;a href=&quot;/&quot;&gt;aquí&lt;/a&gt; para que te lo volvamos a enviar..
        /// </summary>
        internal static string Compte_desactivat {
            get {
                return ResourceManager.GetString("Compte_desactivat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        internal static string Confirma_password {
            get {
                return ResourceManager.GetString("Confirma_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactar.
        /// </summary>
        internal static string Contacta {
            get {
                return ResourceManager.GetString("Contacta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        internal static string Correu_electronic {
            get {
                return ResourceManager.GetString("Correu_electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos se han actualizado correctamente..
        /// </summary>
        internal static string Dades_actualitzades {
            get {
                return ResourceManager.GetString("Dades_actualitzades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de creación.
        /// </summary>
        internal static string Data_creacio {
            get {
                return ResourceManager.GetString("Data_creacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de últ. modificación.
        /// </summary>
        internal static string Data_modificat {
            get {
                return ResourceManager.GetString("Data_modificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        internal static string Data_naixement {
            get {
                return ResourceManager.GetString("Data_naixement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarga el documento.
        /// </summary>
        internal static string Descarregar_document {
            get {
                return ResourceManager.GetString("Descarregar_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe ningún documento con éste identificador..
        /// </summary>
        internal static string Document_no_existeix {
            get {
                return ResourceManager.GetString("Document_no_existeix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mujer.
        /// </summary>
        internal static string Dona {
            get {
                return ResourceManager.GetString("Dona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los derechos reservados.
        /// </summary>
        internal static string Drets_reservats {
            get {
                return ResourceManager.GetString("Drets_reservats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario registrado con esta dirección de correo electrónico..
        /// </summary>
        internal static string Email_ja_existent {
            get {
                return ResourceManager.GetString("Email_ja_existent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos se han actualizado correctamente. Sin embargo, no podrás entrar hasta que hayas activado la nueva dirección de correo electrónico. Comprueba tu bandeja de entrada y haz click en el enlace que te hemos enviado..
        /// </summary>
        internal static string Email_modificat {
            get {
                return ResourceManager.GetString("Email_modificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimado [[NOM]],&lt;br/&gt;&lt;br/&gt;Para completar el registro en HotNotes, visita el siguiente enlace: &lt;a href=&quot;[[LINK]]&quot;&gt;[[LINK]]&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;Atentamente,&lt;br/&gt;&lt;b&gt;El equipo de HotNotes&lt;/b&gt;..
        /// </summary>
        internal static string Email_registre {
            get {
                return ResourceManager.GetString("Email_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha habido un error durante el proceso de activación. Por favor, pruébalo de nuevo en unos minutos.&lt;br /&gt;Si el problema persiste, contacta con el administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Error_activar {
            get {
                return ResourceManager.GetString("Error_activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha habido un error al subir el archivo. Por favor, inténtalo pasados unos minutos..
        /// </summary>
        internal static string Error_Amazon_S3 {
            get {
                return ResourceManager.GetString("Error_Amazon_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha habido un error enviando tu comentario. Por favor, inténtalo de nuevo más tarde..
        /// </summary>
        internal static string Error_comentant {
            get {
                return ResourceManager.GetString("Error_comentant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error cargando los comentarios.
        /// </summary>
        internal static string Error_comentaris {
            get {
                return ResourceManager.GetString("Error_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha habido un error desconocido..
        /// </summary>
        internal static string Error_desconegut {
            get {
                return ResourceManager.GetString("Error_desconegut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha habido un error al subir el documento. Por favor, vuelve a intentarlo en unos minutos..
        /// </summary>
        internal static string Error_pujar_document {
            get {
                return ResourceManager.GetString("Error_pujar_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha habido un error durante el proceso de registro. Por favor, pruébalo de nuevo en unos minutos.&lt;br /&gt;Si el problema persiste, contacta con el administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Error_registre {
            get {
                return ResourceManager.GetString("Error_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe un comentario..
        /// </summary>
        internal static string Escriu_un_comentari {
            get {
                return ResourceManager.GetString("Escriu_un_comentari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Es un examen corregido?.
        /// </summary>
        internal static string Es_examen_corregit {
            get {
                return ResourceManager.GetString("Es_examen_corregit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examen.
        /// </summary>
        internal static string Examen {
            get {
                return ResourceManager.GetString("Examen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exámenes.
        /// </summary>
        internal static string Examens {
            get {
                return ResourceManager.GetString("Examens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        internal static string Fitxer {
            get {
                return ResourceManager.GetString("Fitxer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hombre.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string Inici {
            get {
                return ResourceManager.GetString("Inici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        internal static string Inicia_sessio {
            get {
                return ResourceManager.GetString("Inicia_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlace externo.
        /// </summary>
        internal static string LinkExtern {
            get {
                return ResourceManager.GetString("LinkExtern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlace a YouTube.
        /// </summary>
        internal static string LinkYoutube {
            get {
                return ResourceManager.GetString("LinkYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes ser mayor de edad para registrarte en HotNotes..
        /// </summary>
        internal static string Major_edat {
            get {
                return ResourceManager.GetString("Major_edat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .doc, .docx, .ppt, .pptx, .odt, .pdf o .txt..
        /// </summary>
        internal static string MimeType_no_practiques {
            get {
                return ResourceManager.GetString("MimeType_no_practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de archivo subido no está soportado. Por favor, sube un archivo que tenga uno de los siguientes formatos:.
        /// </summary>
        internal static string MimeType_no_suportat {
            get {
                return ResourceManager.GetString("MimeType_no_suportat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .doc, .docx, .ppt, .pptx, .odt, .pdf, .txt o .zip..
        /// </summary>
        internal static string MimeType_practiques {
            get {
                return ResourceManager.GetString("MimeType_practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar datos.
        /// </summary>
        internal static string Modificar_dades {
            get {
                return ResourceManager.GetString("Modificar_dades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No especificado.
        /// </summary>
        internal static string No_especificat {
            get {
                return ResourceManager.GetString("No_especificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningún comentario en este documento..
        /// </summary>
        internal static string No_hi_ha_comentaris {
            get {
                return ResourceManager.GetString("No_hi_ha_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cerrar la sesión automáticamente.
        /// </summary>
        internal static string No_tanquis_sessio {
            get {
                return ResourceManager.GetString("No_tanquis_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper.
        /// </summary>
        internal static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papers.
        /// </summary>
        internal static string Papers {
            get {
                return ResourceManager.GetString("Papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden..
        /// </summary>
        internal static string Passwords_no_coincideixen {
            get {
                return ResourceManager.GetString("Passwords_no_coincideixen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener como mínimo 6 caracteres..
        /// </summary>
        internal static string Password_curta {
            get {
                return ResourceManager.GetString("Password_curta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto final de carrera.
        /// </summary>
        internal static string PFC {
            get {
                return ResourceManager.GetString("PFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFCs.
        /// </summary>
        internal static string PFCs {
            get {
                return ResourceManager.GetString("PFCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Práctica.
        /// </summary>
        internal static string Practica {
            get {
                return ResourceManager.GetString("Practica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prácticas.
        /// </summary>
        internal static string Practiques {
            get {
                return ResourceManager.GetString("Practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir.
        /// </summary>
        internal static string Pujar {
            get {
                return ResourceManager.GetString("Pujar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir documento.
        /// </summary>
        internal static string Pujar_Document {
            get {
                return ResourceManager.GetString("Pujar_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate.
        /// </summary>
        internal static string Registrat {
            get {
                return ResourceManager.GetString("Registrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se ha completado satisfactoriamente. Sin embargo, antes de poder entrar, debes revisar tu dirección de correo y hacer click en el enlace que te hemos enviado para activar tu cuenta..
        /// </summary>
        internal static string Registre_completat {
            get {
                return ResourceManager.GetString("Registre_completat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        internal static string Ruta {
            get {
                return ResourceManager.GetString("Ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        internal static string Sexe {
            get {
                return ResourceManager.GetString("Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de HotNotes....
        /// </summary>
        internal static string Sobre_HotNotes {
            get {
                return ResourceManager.GetString("Sobre_HotNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        internal static string Tanca_sessio {
            get {
                return ResourceManager.GetString("Tanca_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string Tipus {
            get {
                return ResourceManager.GetString("Tipus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajo.
        /// </summary>
        internal static string Treball {
            get {
                return ResourceManager.GetString("Treball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajos.
        /// </summary>
        internal static string Treballs {
            get {
                return ResourceManager.GetString("Treballs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario debe tener como mínimo 6 caracteres..
        /// </summary>
        internal static string Username_curt {
            get {
                return ResourceManager.GetString("Username_curt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario o la contraseña introducidos son incorrectos.
        /// </summary>
        internal static string Username_password_incorrecte {
            get {
                return ResourceManager.GetString("Username_password_incorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este nombre de usuario ya existe. Por favor, elije otro..
        /// </summary>
        internal static string Usuari_ja_existent {
            get {
                return ResourceManager.GetString("Usuari_ja_existent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe ningún usuario con éste código..
        /// </summary>
        internal static string Usuari_no_existeix {
            get {
                return ResourceManager.GetString("Usuari_no_existeix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión.
        /// </summary>
        internal static string Versio {
            get {
                return ResourceManager.GetString("Versio", resourceCulture);
            }
        }
    }
}
