//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_ca {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_ca() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.language_ca", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apunts.
        /// </summary>
        internal static string Apunts {
            get {
                return ResourceManager.GetString("Apunts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introdueix els termes de cerca....
        /// </summary>
        internal static string Cercador {
            get {
                return ResourceManager.GetString("Cercador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string Cercar {
            get {
                return ResourceManager.GetString("Cercar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognoms.
        /// </summary>
        internal static string Cognoms {
            get {
                return ResourceManager.GetString("Cognoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquest compte d&apos;usuari encara no ha estat activat. Si us plau, revisa la bústia d&apos;entrada i fes clic a l&apos;enllaç que trobaràs al nostre correu.&lt;br /&gt;Si no has rebut cap correu, fes clic &lt;a href=&quot;/&quot;&gt;aquí&lt;/a&gt; per a que te&apos;l tornem a enviar..
        /// </summary>
        internal static string Compte_desactivat {
            get {
                return ResourceManager.GetString("Compte_desactivat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contrasenya.
        /// </summary>
        internal static string Confirma_password {
            get {
                return ResourceManager.GetString("Confirma_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacta.
        /// </summary>
        internal static string Contacta {
            get {
                return ResourceManager.GetString("Contacta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correu electrònic.
        /// </summary>
        internal static string Correu_electronic {
            get {
                return ResourceManager.GetString("Correu_electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de naixement.
        /// </summary>
        internal static string Data_naixement {
            get {
                return ResourceManager.GetString("Data_naixement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dona.
        /// </summary>
        internal static string Dona {
            get {
                return ResourceManager.GetString("Dona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tots els drets reservats.
        /// </summary>
        internal static string Drets_reservats {
            get {
                return ResourceManager.GetString("Drets_reservats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examens.
        /// </summary>
        internal static string Examens {
            get {
                return ResourceManager.GetString("Examens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inici.
        /// </summary>
        internal static string Inici {
            get {
                return ResourceManager.GetString("Inici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sessió.
        /// </summary>
        internal static string Inicia_sessio {
            get {
                return ResourceManager.GetString("Inicia_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No especificat.
        /// </summary>
        internal static string No_especificat {
            get {
                return ResourceManager.GetString("No_especificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tanquis la sessió automàticament.
        /// </summary>
        internal static string No_tanquis_sessio {
            get {
                return ResourceManager.GetString("No_tanquis_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papers.
        /// </summary>
        internal static string Papers {
            get {
                return ResourceManager.GetString("Papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrasenya.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFCs.
        /// </summary>
        internal static string PFCs {
            get {
                return ResourceManager.GetString("PFCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pràctiques.
        /// </summary>
        internal static string Practiques {
            get {
                return ResourceManager.GetString("Practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístra&apos;t.
        /// </summary>
        internal static string Registrat {
            get {
                return ResourceManager.GetString("Registrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexe.
        /// </summary>
        internal static string Sexe {
            get {
                return ResourceManager.GetString("Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre HotNotes....
        /// </summary>
        internal static string Sobre_HotNotes {
            get {
                return ResourceManager.GetString("Sobre_HotNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanca sessió.
        /// </summary>
        internal static string Tanca_sessio {
            get {
                return ResourceManager.GetString("Tanca_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treballs.
        /// </summary>
        internal static string Treballs {
            get {
                return ResourceManager.GetString("Treballs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;usuari.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nom d&apos;usuari o la contrasenya introduïts són incorrectes.
        /// </summary>
        internal static string Username_password_incorrecte {
            get {
                return ResourceManager.GetString("Username_password_incorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquest nom d&apos;usuari ja existeix. Si us plau, tria&apos;n un altre..
        /// </summary>
        internal static string Usuari_ja_existent {
            get {
                return ResourceManager.GetString("Usuari_ja_existent", resourceCulture);
            }
        }
    }
}
