//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_es() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.language_es", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta se ha activado correctamente. Ahora ya puedes iniciar sesión desde la página principal..
        /// </summary>
        internal static string Activar_correcte {
            get {
                return ResourceManager.GetString("Activar_correcte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros....
        /// </summary>
        internal static string Altres {
            get {
                return ResourceManager.GetString("Altres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        internal static string Angles {
            get {
                return ResourceManager.GetString("Angles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apuntes.
        /// </summary>
        internal static string Apunts {
            get {
                return ResourceManager.GetString("Apunts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículos.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura.
        /// </summary>
        internal static string Assignatura {
            get {
                return ResourceManager.GetString("Assignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor.
        /// </summary>
        internal static string Autor {
            get {
                return ResourceManager.GetString("Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        internal static string Benvingut {
            get {
                return ResourceManager.GetString("Benvingut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando.
        /// </summary>
        internal static string Carregant {
            get {
                return ResourceManager.GetString("Carregant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando comentarios....
        /// </summary>
        internal static string Carregant_comentaris {
            get {
                return ResourceManager.GetString("Carregant_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Castellano.
        /// </summary>
        internal static string Castella {
            get {
                return ResourceManager.GetString("Castella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalán.
        /// </summary>
        internal static string Catala {
            get {
                return ResourceManager.GetString("Catala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce los términos de búsqueda....
        /// </summary>
        internal static string Cercador {
            get {
                return ResourceManager.GetString("Cercador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Cercar {
            get {
                return ResourceManager.GetString("Cercar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de activación es incorrecto. Si éste es el enlace que te hemos enviado a tu correo, por favor, contacta con el administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Codi_activar_incorrecte {
            get {
                return ResourceManager.GetString("Codi_activar_incorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string Cognoms {
            get {
                return ResourceManager.GetString("Cognoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completa el registro en HotNotes.
        /// </summary>
        internal static string Completa_el_registre {
            get {
                return ResourceManager.GetString("Completa_el_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta cuenta de usuario aún no ha sido activada. Por favor, revisa la bandeja de entrada y haz click en el enlace que encontrarás en nuestro correo.&lt;br /&gt;Si no has recibido ningún correo, haz click &lt;a href=&quot;/&quot;&gt;aquí&lt;/a&gt; para que te lo volvamos a enviar..
        /// </summary>
        internal static string Compte_desactivat {
            get {
                return ResourceManager.GetString("Compte_desactivat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        internal static string Confirma_password {
            get {
                return ResourceManager.GetString("Confirma_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactar.
        /// </summary>
        internal static string Contacta {
            get {
                return ResourceManager.GetString("Contacta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        internal static string Correu_electronic {
            get {
                return ResourceManager.GetString("Correu_electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos se han actualizado correctamente..
        /// </summary>
        internal static string Dades_actualitzades {
            get {
                return ResourceManager.GetString("Dades_actualitzades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de creación.
        /// </summary>
        internal static string Data_creacio {
            get {
                return ResourceManager.GetString("Data_creacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de últ. modificación.
        /// </summary>
        internal static string Data_modificat {
            get {
                return ResourceManager.GetString("Data_modificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        internal static string Data_naixement {
            get {
                return ResourceManager.GetString("Data_naixement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descarga el documento.
        /// </summary>
        internal static string Descarregar_document {
            get {
                return ResourceManager.GetString("Descarregar_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos de la asignatura.
        /// </summary>
        internal static string Documents_assignatura {
            get {
                return ResourceManager.GetString("Documents_assignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos del usuario.
        /// </summary>
        internal static string Documents_usuari {
            get {
                return ResourceManager.GetString("Documents_usuari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe ningún documento con éste identificador..
        /// </summary>
        internal static string Document_no_existeix {
            get {
                return ResourceManager.GetString("Document_no_existeix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mujer.
        /// </summary>
        internal static string Dona {
            get {
                return ResourceManager.GetString("Dona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los derechos reservados.
        /// </summary>
        internal static string Drets_reservats {
            get {
                return ResourceManager.GetString("Drets_reservats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay resultados.
        /// </summary>
        internal static string DT_sEmptyTable {
            get {
                return ResourceManager.GetString("DT_sEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primero.
        /// </summary>
        internal static string DT_sFirst {
            get {
                return ResourceManager.GetString("DT_sFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrando _START_-_END_ de _TOTAL_ resultados.
        /// </summary>
        internal static string DT_sInfo {
            get {
                return ResourceManager.GetString("DT_sInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrando 0 de 0 resultados.
        /// </summary>
        internal static string DT_sInfoEmpty {
            get {
                return ResourceManager.GetString("DT_sInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (filtrados de _MAX_ resultados totales).
        /// </summary>
        internal static string DT_sInfoFiltered {
            get {
                return ResourceManager.GetString("DT_sInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Último.
        /// </summary>
        internal static string DT_sLast {
            get {
                return ResourceManager.GetString("DT_sLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver _MENU_ resultados.
        /// </summary>
        internal static string DT_sLengthMenu {
            get {
                return ResourceManager.GetString("DT_sLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string DT_sNext {
            get {
                return ResourceManager.GetString("DT_sNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        internal static string DT_sPrevious {
            get {
                return ResourceManager.GetString("DT_sPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obteniendo resultados....
        /// </summary>
        internal static string DT_sProcessing {
            get {
                return ResourceManager.GetString("DT_sProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar: .
        /// </summary>
        internal static string DT_sSearch {
            get {
                return ResourceManager.GetString("DT_sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay resultados.
        /// </summary>
        internal static string DT_sZeroRecords {
            get {
                return ResourceManager.GetString("DT_sZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un usuario registrado con esta dirección de correo electrónico..
        /// </summary>
        internal static string Email_ja_existent {
            get {
                return ResourceManager.GetString("Email_ja_existent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos se han actualizado correctamente. Sin embargo, no podrás entrar hasta que hayas activado la nueva dirección de correo electrónico. Comprueba tu bandeja de entrada y haz click en el enlace que te hemos enviado..
        /// </summary>
        internal static string Email_modificat {
            get {
                return ResourceManager.GetString("Email_modificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimado [[NOM]],&lt;br/&gt;&lt;br/&gt;Para completar el registro en HotNotes, visita el siguiente enlace: &lt;a href=&quot;[[LINK]]&quot;&gt;[[LINK]]&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;Atentamente,&lt;br/&gt;&lt;b&gt;El equipo de HotNotes&lt;/b&gt;..
        /// </summary>
        internal static string Email_registre {
            get {
                return ResourceManager.GetString("Email_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un error durante el proceso de activación. Por favor, pruébalo de nuevo en unos minutos.&lt;br /&gt;Si el problema persiste, contacta con el administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Error_activar {
            get {
                return ResourceManager.GetString("Error_activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un error al subir el archivo. Por favor, inténtalo pasados unos minutos..
        /// </summary>
        internal static string Error_Amazon_S3 {
            get {
                return ResourceManager.GetString("Error_Amazon_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un error enviando tu comentario. Por favor, inténtalo de nuevo más tarde..
        /// </summary>
        internal static string Error_comentant {
            get {
                return ResourceManager.GetString("Error_comentant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cargando los comentarios.
        /// </summary>
        internal static string Error_comentaris {
            get {
                return ResourceManager.GetString("Error_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un error desconocido..
        /// </summary>
        internal static string Error_desconegut {
            get {
                return ResourceManager.GetString("Error_desconegut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado ninguna assignatura con este Id..
        /// </summary>
        internal static string Error_id_assignatura {
            get {
                return ResourceManager.GetString("Error_id_assignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado ningún usuario con este Id..
        /// </summary>
        internal static string Error_id_usuari {
            get {
                return ResourceManager.GetString("Error_id_usuari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No te puedes dessubscribir de un usuari al que no estás subscrito..
        /// </summary>
        internal static string Error_no_subscrit {
            get {
                return ResourceManager.GetString("Error_no_subscrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un error al subir el documento. Por favor, vuelve a intentarlo en unos minutos..
        /// </summary>
        internal static string Error_pujar_document {
            get {
                return ResourceManager.GetString("Error_pujar_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un error durante el proceso de registro. Por favor, pruébalo de nuevo en unos minutos.&lt;br /&gt;Si el problema persiste, contacta con el administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Error_registre {
            get {
                return ResourceManager.GetString("Error_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un error al subscribirse a este usuario. Por favor, vuelve a intentarlo en unos instantes..
        /// </summary>
        internal static string Error_subscriure {
            get {
                return ResourceManager.GetString("Error_subscriure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un error al valorar este documento. Por favor, vuelve a intentarlo más tarde..
        /// </summary>
        internal static string Error_valoracio {
            get {
                return ResourceManager.GetString("Error_valoracio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe un comentario..
        /// </summary>
        internal static string Escriu_un_comentari {
            get {
                return ResourceManager.GetString("Escriu_un_comentari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Es un examen corregido?.
        /// </summary>
        internal static string Es_examen_corregit {
            get {
                return ResourceManager.GetString("Es_examen_corregit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Examen.
        /// </summary>
        internal static string Examen {
            get {
                return ResourceManager.GetString("Examen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exámenes.
        /// </summary>
        internal static string Examens {
            get {
                return ResourceManager.GetString("Examens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        internal static string Fitxer {
            get {
                return ResourceManager.GetString("Fitxer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hombre.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string Inici {
            get {
                return ResourceManager.GetString("Inici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string Inicia_sessio {
            get {
                return ResourceManager.GetString("Inicia_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enlace externo.
        /// </summary>
        internal static string LinkExtern {
            get {
                return ResourceManager.GetString("LinkExtern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enlace a YouTube.
        /// </summary>
        internal static string LinkYoutube {
            get {
                return ResourceManager.GetString("LinkYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ser mayor de edad para registrarte en HotNotes..
        /// </summary>
        internal static string Major_edat {
            get {
                return ResourceManager.GetString("Major_edat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .doc, .docx, .ppt, .pptx, .odt, .pdf o .txt..
        /// </summary>
        internal static string MimeType_no_practiques {
            get {
                return ResourceManager.GetString("MimeType_no_practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de archivo subido no está soportado. Por favor, sube un archivo que tenga uno de los siguientes formatos:.
        /// </summary>
        internal static string MimeType_no_suportat {
            get {
                return ResourceManager.GetString("MimeType_no_suportat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .doc, .docx, .ppt, .pptx, .odt, .pdf, .txt o .zip..
        /// </summary>
        internal static string MimeType_practiques {
            get {
                return ResourceManager.GetString("MimeType_practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar datos.
        /// </summary>
        internal static string Modificar_dades {
            get {
                return ResourceManager.GetString("Modificar_dades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No especificado.
        /// </summary>
        internal static string No_especificat {
            get {
                return ResourceManager.GetString("No_especificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ningún comentario en este documento..
        /// </summary>
        internal static string No_hi_ha_comentaris {
            get {
                return ResourceManager.GetString("No_hi_ha_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No cerrar la sesión automáticamente.
        /// </summary>
        internal static string No_tanquis_sessio {
            get {
                return ResourceManager.GetString("No_tanquis_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paper.
        /// </summary>
        internal static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Papers.
        /// </summary>
        internal static string Papers {
            get {
                return ResourceManager.GetString("Papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        internal static string Passwords_no_coincideixen {
            get {
                return ResourceManager.GetString("Passwords_no_coincideixen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener como mínimo 6 caracteres..
        /// </summary>
        internal static string Password_curta {
            get {
                return ResourceManager.GetString("Password_curta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto final de carrera.
        /// </summary>
        internal static string PFC {
            get {
                return ResourceManager.GetString("PFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PFCs.
        /// </summary>
        internal static string PFCs {
            get {
                return ResourceManager.GetString("PFCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Práctica.
        /// </summary>
        internal static string Practica {
            get {
                return ResourceManager.GetString("Practica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prácticas.
        /// </summary>
        internal static string Practiques {
            get {
                return ResourceManager.GetString("Practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir.
        /// </summary>
        internal static string Pujar {
            get {
                return ResourceManager.GetString("Pujar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir documento.
        /// </summary>
        internal static string Pujar_Document {
            get {
                return ResourceManager.GetString("Pujar_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        internal static string Registrat {
            get {
                return ResourceManager.GetString("Registrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro se ha completado satisfactoriamente. Sin embargo, antes de poder entrar, debes revisar tu dirección de correo y hacer click en el enlace que te hemos enviado para activar tu cuenta..
        /// </summary>
        internal static string Registre_completat {
            get {
                return ResourceManager.GetString("Registre_completat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta.
        /// </summary>
        internal static string Ruta {
            get {
                return ResourceManager.GetString("Ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo.
        /// </summary>
        internal static string Sexe {
            get {
                return ResourceManager.GetString("Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de HotNotes....
        /// </summary>
        internal static string Sobre_HotNotes {
            get {
                return ResourceManager.GetString("Sobre_HotNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string Tanca_sessio {
            get {
                return ResourceManager.GetString("Tanca_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string Tipus {
            get {
                return ResourceManager.GetString("Tipus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajo.
        /// </summary>
        internal static string Treball {
            get {
                return ResourceManager.GetString("Treball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajos.
        /// </summary>
        internal static string Treballs {
            get {
                return ResourceManager.GetString("Treballs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario debe tener como mínimo 6 caracteres..
        /// </summary>
        internal static string Username_curt {
            get {
                return ResourceManager.GetString("Username_curt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario o la contraseña introducidos son incorrectos.
        /// </summary>
        internal static string Username_password_incorrecte {
            get {
                return ResourceManager.GetString("Username_password_incorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este nombre de usuario ya existe. Por favor, elije otro..
        /// </summary>
        internal static string Usuari_ja_existent {
            get {
                return ResourceManager.GetString("Usuari_ja_existent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe ningún usuario con éste código..
        /// </summary>
        internal static string Usuari_no_existeix {
            get {
                return ResourceManager.GetString("Usuari_no_existeix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración.
        /// </summary>
        internal static string Valoracio {
            get {
                return ResourceManager.GetString("Valoracio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión.
        /// </summary>
        internal static string Versio {
            get {
                return ResourceManager.GetString("Versio", resourceCulture);
            }
        }
    }
}
