//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_ca {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_ca() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.language_ca", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El compte s&apos;ha activat correctament. Ara ja pots iniciar sessió des de la pàgina principal..
        /// </summary>
        internal static string Activar_correcte {
            get {
                return ResourceManager.GetString("Activar_correcte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altres....
        /// </summary>
        internal static string Altres {
            get {
                return ResourceManager.GetString("Altres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglés.
        /// </summary>
        internal static string Angles {
            get {
                return ResourceManager.GetString("Angles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apunts.
        /// </summary>
        internal static string Apunts {
            get {
                return ResourceManager.GetString("Apunts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignatura.
        /// </summary>
        internal static string Assignatura {
            get {
                return ResourceManager.GetString("Assignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string Autor {
            get {
                return ResourceManager.GetString("Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregant.
        /// </summary>
        internal static string Carregant {
            get {
                return ResourceManager.GetString("Carregant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregant comentaris....
        /// </summary>
        internal static string Carregant_comentaris {
            get {
                return ResourceManager.GetString("Carregant_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castellà.
        /// </summary>
        internal static string Castella {
            get {
                return ResourceManager.GetString("Castella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Català.
        /// </summary>
        internal static string Catala {
            get {
                return ResourceManager.GetString("Catala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introdueix els termes de cerca....
        /// </summary>
        internal static string Cercador {
            get {
                return ResourceManager.GetString("Cercador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string Cercar {
            get {
                return ResourceManager.GetString("Cercar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codi d&apos;activació és incorrecte. Si aquest és l&apos;enllaç que t&apos;hem enviat al teu correu, si us plau, contacta amb l&apos;administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Codi_activar_incorrecte {
            get {
                return ResourceManager.GetString("Codi_activar_incorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognoms.
        /// </summary>
        internal static string Cognoms {
            get {
                return ResourceManager.GetString("Cognoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completa el registre a HotNotes.
        /// </summary>
        internal static string Completa_el_registre {
            get {
                return ResourceManager.GetString("Completa_el_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquest compte d&apos;usuari encara no ha estat activat. Si us plau, revisa la bústia d&apos;entrada i fes clic a l&apos;enllaç que trobaràs al nostre correu.&lt;br /&gt;Si no has rebut cap correu, fes clic &lt;a href=&quot;/&quot;&gt;aquí&lt;/a&gt; per a que te&apos;l tornem a enviar..
        /// </summary>
        internal static string Compte_desactivat {
            get {
                return ResourceManager.GetString("Compte_desactivat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contrasenya.
        /// </summary>
        internal static string Confirma_password {
            get {
                return ResourceManager.GetString("Confirma_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacta.
        /// </summary>
        internal static string Contacta {
            get {
                return ResourceManager.GetString("Contacta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correu electrònic.
        /// </summary>
        internal static string Correu_electronic {
            get {
                return ResourceManager.GetString("Correu_electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les dades s&apos;han actualitzat correctament..
        /// </summary>
        internal static string Dades_actualitzades {
            get {
                return ResourceManager.GetString("Dades_actualitzades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de creació.
        /// </summary>
        internal static string Data_creacio {
            get {
                return ResourceManager.GetString("Data_creacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data d&apos;últ. modificació.
        /// </summary>
        internal static string Data_modificat {
            get {
                return ResourceManager.GetString("Data_modificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de naixement.
        /// </summary>
        internal static string Data_naixement {
            get {
                return ResourceManager.GetString("Data_naixement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarrega el document.
        /// </summary>
        internal static string Descarregar_document {
            get {
                return ResourceManager.GetString("Descarregar_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existeix cap document amb aquest identificador..
        /// </summary>
        internal static string Document_no_existeix {
            get {
                return ResourceManager.GetString("Document_no_existeix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dona.
        /// </summary>
        internal static string Dona {
            get {
                return ResourceManager.GetString("Dona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tots els drets reservats.
        /// </summary>
        internal static string Drets_reservats {
            get {
                return ResourceManager.GetString("Drets_reservats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja hi ha un usuari registrat amb aquesta adreça de correu electrònic..
        /// </summary>
        internal static string Email_ja_existent {
            get {
                return ResourceManager.GetString("Email_ja_existent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les dades s&apos;han actualitzat correctament. Tot i així, no podràs entrar fins que hagis activat la nova direcció de correu electrònic. Comprova la teva bústia d&apos;entrada i fes clic a l&apos;enllaç que t&apos;hem enviat..
        /// </summary>
        internal static string Email_modificat {
            get {
                return ResourceManager.GetString("Email_modificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimat [[NOM]],&lt;br/&gt;&lt;br/&gt;Per a completar el registre a HotNotes, visita el següent enllaç: &lt;a href=&quot;[[LINK]]&quot;&gt;[[LINK]]&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;Atentament,&lt;br/&gt;&lt;b&gt;L&apos;equip de HotNotes&lt;/b&gt;..
        /// </summary>
        internal static string Email_registre {
            get {
                return ResourceManager.GetString("Email_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi ha hagut un error durant el procés d&apos;activació. Si us plau, torna-ho a provar en uns minuts.&lt;br /&gt;Si el problema persisteix, contacta amb l&apos;administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Error_activar {
            get {
                return ResourceManager.GetString("Error_activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi ha hagut un error enviant el teu comentari. Si us plau, torna-ho a intentar més tard..
        /// </summary>
        internal static string Error_comentant {
            get {
                return ResourceManager.GetString("Error_comentant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error carregant els comentaris.
        /// </summary>
        internal static string Error_comentaris {
            get {
                return ResourceManager.GetString("Error_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi ha hagut un error al pujar el document. Si us plau, torna-ho a provar en uns minuts..
        /// </summary>
        internal static string Error_pujar_document {
            get {
                return ResourceManager.GetString("Error_pujar_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi ha hagut un error durant el procés de registre. Si us plau, torna-ho a provar en uns minuts.&lt;br /&gt;Si el problema persisteix, contacta amb l&apos;administrador: &lt;a href=&quot;mailto:jonathan.clara.marquez@gmail.com&quot;&gt;jonathan.clara.marquez@gmail.com&lt;/a&gt;.
        /// </summary>
        internal static string Error_registre {
            get {
                return ResourceManager.GetString("Error_registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriu un comentari..
        /// </summary>
        internal static string Escriu_un_comentari {
            get {
                return ResourceManager.GetString("Escriu_un_comentari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exàmen.
        /// </summary>
        internal static string Examen {
            get {
                return ResourceManager.GetString("Examen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examens.
        /// </summary>
        internal static string Examens {
            get {
                return ResourceManager.GetString("Examens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inici.
        /// </summary>
        internal static string Inici {
            get {
                return ResourceManager.GetString("Inici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sessió.
        /// </summary>
        internal static string Inicia_sessio {
            get {
                return ResourceManager.GetString("Inicia_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enllaç extern.
        /// </summary>
        internal static string LinkExtern {
            get {
                return ResourceManager.GetString("LinkExtern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enllaç a YouTube.
        /// </summary>
        internal static string LinkYoutube {
            get {
                return ResourceManager.GetString("LinkYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has de ser major d&apos;edat per a registrar-te a HotNotes..
        /// </summary>
        internal static string Major_edat {
            get {
                return ResourceManager.GetString("Major_edat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .doc, .docx, .ppt, .pptx, .odt, .pdf o .txt..
        /// </summary>
        internal static string MimeType_no_practiques {
            get {
                return ResourceManager.GetString("MimeType_no_practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipus d&apos;arxiu pujat no està suportat. Si us plau, puja un arxiu que tingui un dels següents formats:.
        /// </summary>
        internal static string MimeType_no_suportat {
            get {
                return ResourceManager.GetString("MimeType_no_suportat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .doc, .docx, .ppt, .pptx, .odt, .pdf, .txt o .zip..
        /// </summary>
        internal static string MimeType_practiques {
            get {
                return ResourceManager.GetString("MimeType_practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar dades.
        /// </summary>
        internal static string Modificar_dades {
            get {
                return ResourceManager.GetString("Modificar_dades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No especificat.
        /// </summary>
        internal static string No_especificat {
            get {
                return ResourceManager.GetString("No_especificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hi ha cap comentari en aquest document..
        /// </summary>
        internal static string No_hi_ha_comentaris {
            get {
                return ResourceManager.GetString("No_hi_ha_comentaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tanquis la sessió automàticament.
        /// </summary>
        internal static string No_tanquis_sessio {
            get {
                return ResourceManager.GetString("No_tanquis_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper.
        /// </summary>
        internal static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papers.
        /// </summary>
        internal static string Papers {
            get {
                return ResourceManager.GetString("Papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrasenya.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les contrasenyes no coincideixen..
        /// </summary>
        internal static string Passwords_no_coincideixen {
            get {
                return ResourceManager.GetString("Passwords_no_coincideixen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contrasenya ha de tenir com a mínim 6 caràcters..
        /// </summary>
        internal static string Password_curta {
            get {
                return ResourceManager.GetString("Password_curta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projecte final de carrera.
        /// </summary>
        internal static string PFC {
            get {
                return ResourceManager.GetString("PFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFCs.
        /// </summary>
        internal static string PFCs {
            get {
                return ResourceManager.GetString("PFCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pràctica.
        /// </summary>
        internal static string Practica {
            get {
                return ResourceManager.GetString("Practica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pràctiques.
        /// </summary>
        internal static string Practiques {
            get {
                return ResourceManager.GetString("Practiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pujar document.
        /// </summary>
        internal static string Pujar_Document {
            get {
                return ResourceManager.GetString("Pujar_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar-se.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístra&apos;t.
        /// </summary>
        internal static string Registrat {
            get {
                return ResourceManager.GetString("Registrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registre s&apos;ha completat satisfactòriament. No obstant, abans de poder entrar, has de revisar la teva direcció de correu i fer clic a l&apos;enllaç que t&apos;hem enviat per activar el teu compte..
        /// </summary>
        internal static string Registre_completat {
            get {
                return ResourceManager.GetString("Registre_completat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexe.
        /// </summary>
        internal static string Sexe {
            get {
                return ResourceManager.GetString("Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre HotNotes....
        /// </summary>
        internal static string Sobre_HotNotes {
            get {
                return ResourceManager.GetString("Sobre_HotNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanca sessió.
        /// </summary>
        internal static string Tanca_sessio {
            get {
                return ResourceManager.GetString("Tanca_sessio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipus.
        /// </summary>
        internal static string Tipus {
            get {
                return ResourceManager.GetString("Tipus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treball.
        /// </summary>
        internal static string Treball {
            get {
                return ResourceManager.GetString("Treball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treballs.
        /// </summary>
        internal static string Treballs {
            get {
                return ResourceManager.GetString("Treballs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;usuari.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nom d&apos;usuari ha de tenir com a mínim 6 caràcters..
        /// </summary>
        internal static string Username_curt {
            get {
                return ResourceManager.GetString("Username_curt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nom d&apos;usuari o la contrasenya introduïts són incorrectes.
        /// </summary>
        internal static string Username_password_incorrecte {
            get {
                return ResourceManager.GetString("Username_password_incorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquest nom d&apos;usuari ja existeix. Si us plau, tria&apos;n un altre..
        /// </summary>
        internal static string Usuari_ja_existent {
            get {
                return ResourceManager.GetString("Usuari_ja_existent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existeix cap usuari amb aquest codi..
        /// </summary>
        internal static string Usuari_no_existeix {
            get {
                return ResourceManager.GetString("Usuari_no_existeix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versió.
        /// </summary>
        internal static string Versio {
            get {
                return ResourceManager.GetString("Versio", resourceCulture);
            }
        }
    }
}
